server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:
          type: rabbit  #消息组件类型
          environment: #设置rabbitmq相关的配置
            spring:
              rabbitmq:
                host: 49.233.221.89
                port: 5672
                username: admin
                password: admin
      bindings: #服务的整合处理
        input: #通道名称
          destination: studyExchange #要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为json,文本则设置 text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          #group: zwlong
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
    instance-id: receive-8802.com
    prefer-ip-address: true

