server:
  port: 8013

#服务别名  注册consul到服务中心
spring:
  application:
    name: consul-consumerconsul-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://49.233.221.89:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    consul:
      host: 192.168.136.148
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 192.168.136.148