server:
  port: 8014

#服务别名  注册zookeeper到服务中心
spring:
  application:
    name: cloud-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.136.146:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


eureka:
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
#mybatis-plus:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.zwlong.springcloud.entities    # 所有Entity别名类所在包
ribbon:
  #建立连接所用时间，
  ReadTimeout: 5000
  #读取资源等待时间
  ConnectTimeout: 5000

logging:
  level:
    com.zwlong.springcloud.service.PaymentFeignService: debug